### ISSUE TITLE
Is it possible to separate the date line from the buttons?

### ISSUE THREAD

**Issue by webwalrus** [davish/obsidian-full-calendar#201] opened 2022-12-03 20:03 UTC
Currently the header is < > | today | {date} | month week day list

When I try to narrow up the column for "list" view, the date gets super-crunched, ugly, and takes up a ton of vertical space

Nov
27
-
Dec
3,
2022

Could the date line be styled somehow to go *above* everything else, so that it's:

Nov 27 - Dec 3, 2022
<all the buttons>?

**Comment by davish** [comment] 2022-12-03 21:37
Can you send a screenshot please?

**Comment by webwalrus** [comment] 2022-12-04 01:23
Sure. When I narrow up the calendar column to a small part of the screen, it looks like this. I'd like to be able to always have it open, but giving it almost half of my screen so that the date all fits on one line makes it far, far less useful.
![Screenshot 2022-12-03 at 7 21 28 PM](https://user-images.githubusercontent.com/119759749/205469494-9074cc9b-9de9-4ea2-ba06-17891109c660.png)

**Comment by davish** [comment] 2022-12-04 01:29
This is a duplicate of #51.

**Closed by davish** 2022-12-04 01:29 UTC
Labels: question
