### ISSUE TITLE
Daylight Savings Time Issue

### ISSUE THREAD

**Issue by 02202002** [davish/obsidian-full-calendar#307] opened 2023-03-12 08:30 UTC
I have an event scheduled at 2AM every Saturday and Sunday, but because of Daylight Savings Time, I'm running into an issue where despite the event being set to 2AM, the calendar view has it set to 3AM. Any attempts to set it to any time between 2AM and 3AM just sets it an hour ahead (so something like 2:10AM goes to 3:10AM).

<img width="329" alt="Obsidian_hGgWD0kv5a" src="https://user-images.githubusercontent.com/46614473/224533195-0a6d6e81-27d3-423e-a679-d751c9b8413b.png">

<img width="382" alt="Obsidian_vb59QBVRdh" src="https://user-images.githubusercontent.com/46614473/224533216-d90748a4-ee57-4d6b-850c-78774c81a5a5.png">

**Comment by davish** [comment] 2023-03-15 12:09
Thank you for submitting! Right now, the calendar doesn't handle timezones at all, and assumes all dates are in the local time. During a DST transition, the local time actually switches timezones. Therefore I'm closing this issue as a duplicate of #66.

**Closed by davish** 2023-03-15 12:09 UTC
