### ISSUE TITLE
Syncing the Obsidian cal to a Webdav cal

### ISSUE THREAD

**Issue by Tim-Porsch** [davish/obsidian-full-calendar#146] opened 2022-08-27 10:17 UTC
I don't know if this is possible, but I would need to see all the events outside of obsidian on my phone for example, and it would be pretty nice if the local calendar could be synced as a calendar to Nextcloud for example.
Thanks for creating this plugin btw :D

**Comment by mourdani** [comment] 2022-08-30 06:01
yes you can. 
you go to : setting -> Full Calendar -> in "add calendar" select calDAV -> put in your nextcloud dav url which should be yournextcloud.org/remote.php/dav. 
Done. 
Although it is a bit bugy but you can view your events.

**Comment by Bulwagga** [comment] 2022-09-01 13:12
Right now the CALDAV connection (a beautiful thing!) is read only.  Any idea to allow writing to the CALDAV database?

**Comment by MiracleXYZ** [comment] 2022-09-02 11:32
I think this issue means **exporting** the local calendar to a CalDAV server instead of importing an external CalDAV to obsidian. Seems like a dup of #25 .

**Comment by davish** [comment] 2022-10-05 18:50
Thanks @MiracleXYZ, closing this as a duplicate of #25.

**Closed by davish** 2022-10-05 18:50 UTC
