### ISSUE TITLE
Create notes from imported events

### ISSUE THREAD

**Issue by iuryt** [davish/obsidian-full-calendar#276] opened 2023-02-10 15:44 UTC
Hi,

This is an awesome plugin and I am really enjoying starting with the Obsidian world.
I am currently importing my Google Calendar events using the ICal link.
As far as I know, there is no way to make this link bi-directional, right?

Anyway, I can't understand why your plugin doesn't allow me to create notes from imported events.
I would like to use it for taking notes for recurring meetings for example.
What I would expect was that once I click on the event, it would create a note in the format `Event Name - Date` somewhere I could configure in the settings and then I could create my notes for that event.

Maybe I am requesting something that already exists, but I couldn't find that on the docs.

**Comment by cobbenterprises** [comment] 2023-02-12 01:35
Yes, that would be great.

**Comment by davish** [comment] 2023-02-12 03:00
This is a duplicate of #40.

**Closed by davish** 2023-02-12 03:00 UTC
