### ISSUE TITLE
pull out start time of all events of a given day for use for plugin day planner

### ISSUE THREAD

**Issue by rene-koch-alderaan** [davish/obsidian-full-calendar#132] opened 2022-07-17 09:42 UTC
Hi,
thank you for having my CALDAV calendar in my obsidian vault.

I wonder if it would be possible to populate my daily note template with the events in the calendar entry for that date like this.

daily note file name: 2022-07-17

- [ ] 08:00 dentist
- [ ] 09:00 BREAK
- [ ] 10:00 work to do
- [ ] 12:00 lunch

which would fetch the start time of each event in all shown calendars and would be compliant with the day planner plugin structure - to have it right at hand in the daily note...

What do you think - is this possible?

**Comment by davish** [comment] 2022-10-05 19:06
This can be accomplished right now with a dataview query if you are using local calendars: https://github.com/davish/obsidian-full-calendar/issues/143#issuecomment-1227344953. Issue #143 itself tracks allowing this to work with remote calendars.

The eventual goal of PR #103 is that you'll be able to store your events within your daily notes as the source-of-truth. Which is possibly closer to what you want. Closing this issue as a duplicate of #143 and #103.

**Closed by davish** 2022-10-05 19:06 UTC
