### ISSUE TITLE
Daylight saving time

### ISSUE THREAD

**Issue by MrMic** [davish/obsidian-full-calendar#322] opened 2023-03-29 09:30 UTC
**Describe the bug**
Daylight saving time is not taken into account

**To Reproduce**

- Add Google Calendar and all went fine so far, but when we have 
changed to Daylight saving time the previous weekend, now 
it misses one hour although in Google Calendar everything 
is OK!

Can u fix that quickly?

Thanks.
Rgds,

**Comment by davish** [comment] 2023-03-30 01:01
Thanks for submitting! Related to #311, likely.
A few questions:
- Is this for a recurring event or all events?
- What timezone are you in, if you don't mind me asking?

**Comment by davish** [comment] 2023-04-02 13:40
Closing this as a duplicate of #311 and #66.

**Closed by davish** 2023-04-02 13:40 UTC
Labels: bug, timezones
