### ISSUE TITLE
Repeating Events

### ISSUE THREAD

**Issue by Elwood4415** [davish/obsidian-full-calendar#175] opened 2022-11-09 17:11 UTC
One of my big roadblocks for this plug-in is the lack of options for repeating events. As far as I can tell, you can only set it up to repeat events either daily or every week. It would be a big help to be able to set up events to repeat every x number of weeks, every x number of months and even every x number of years. It would also be helpful to have an option to customize repeats. These items are available on many calendars. Thank you for your consideration.

**Comment by davish** [comment] 2022-11-09 18:51
Thanks for submitting! this is a duplicate of #22. This is definitely on the roadmap

**Closed by davish** 2022-11-09 18:51 UTC
