### ISSUE TITLE
Input times in 24 hour format

### ISSUE THREAD

**Issue by artstisen** [davish/obsidian-full-calendar#163] opened 2022-10-23 11:55 UTC
# Description
**The plugin does not support standard European 24 hour time format:**
- In Month view the control create an entry spanning two days when the selected time span extends past noon (see GIF below).
- In the day view the times are shown in 12 hour format even though the system is 24 hour.

## Screenshots

Time span issue in Month view (GIF animation). Selecting a time span across noon creates a two-day event:
![24h-format-issue1](https://user-images.githubusercontent.com/46990511/197390258-8f6d7708-0890-4654-9878-5102aa281b15.gif)

12 hour formatting issue in Week/Day view:
![24h-format-issue2](https://user-images.githubusercontent.com/46990511/197390301-27f01008-a5ea-42ea-9ee4-a101c199a705.png)

## Summary

**The calendar control supports both 12 and 24 hour time formats**
so it would be nice if it was possible to specify, select or auto detect the current locale to insure a useful time format for European users:
https://fullcalendar.io/docs/date-formatting

Thanks for your time in making the plugin available :)

**Comment by davish** [comment] 2022-10-26 15:47
This is related to, but not an exact duplicate of, #33. It should be part of #148 to also change the input elements when the setting is changed.

**Comment by davish** [comment] 2022-11-09 19:01
Apparently there is no way to force a `time` input to use 24-hour time or am/pm time as its input. It relies on the localization settings in the browser/app. Since #33 has been closed, I'm closing this issue as well since it won't be able to be fixed.

**Closed by davish** 2022-11-09 19:01 UTC
Labels: bug, ui, localization

**Comment by locriacyber** [comment] 2022-11-26 22:44
Possible to use custom input element?
