### ISSUE TITLE
Calendar synced from outlook in .ics format broken in new update.

### ISSUE THREAD

**Issue by dykhnoanthony** [davish/obsidian-full-calendar#212] opened 2022-12-05 13:46 UTC
Opening settings to add new .ics format calendars has no dropdown box to add URL

I'm on Windows 10 Pro. 
Obsidian 1.0.3 version.

**Comment by davish** [comment] 2022-12-05 15:59
This seems to be a duplicate of #206. Please follow along there for progress on this bug. Thank you for submitting!

**Closed by davish** 2022-12-05 15:59 UTC
Labels: bug
