### ISSUE TITLE
Fails to display a publicly-shared (personal) iOS ical calendar set up through the plugin.  Also, not displaying the Apple US Holidays ical calendar (webcal://ical.mac.com/ical/US32Holidays.ics).

### ISSUE THREAD

**Issue by claudcameron** [davish/obsidian-full-calendar#89] opened 2022-04-12 15:54 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Console Errors**
Go to `View->Toggle Developer Tools` and open up the JavaScript console, reproduce your bug, and copy/paste any logs you see there.

**Device info (please complete the following information):**

iPad OS 15, iOS 15

 - Plugin Version [e.g. `0.1.3`] 

0.6.1

**Additional context**

**Comment by davish** [comment] 2022-04-21 23:30
@claudcameron I'm closing this issue because you did not fill out the bug template, and so I have no details on how I can possibly reproduce this bug to fix it. If you are still facing this issue, please edit the description, fill out the template, and tag me to reopen it.

Thanks!

**Closed by davish** 2022-04-21 23:30 UTC
Labels: bug
