### ISSUE TITLE
Some Google -> Full Calendar events are 5 hours off

### ISSUE THREAD

**Issue by amyoungil** [davish/obsidian-full-calendar#330] opened 2023-04-02 01:23 UTC
a) I can’t figure out why some events are 5 hours later in Full Calendar, from my Google Calendar.

The five-hour maybe coincidentally happens to be Chicago Time, which is what I’m on. But I created new events with Chicago Time, and some with “Use Current Time Zone” and they are 5 hours off when displayed in Full Calendar.

b) I can’t figure out also why some are, and some aren’t.

I can modify a correct-time event in Google Calendar, and that continues to match the time block in Full Calendar.

But some never matched, and after editing they still don’t match when imported by Full Calendar.

b2) If I Duplicate an event in Google Calendar, it continues to display correctly in Full Calendar. The 14:30 event starts at 2:30pm. The 19:30 event is also supposed to start 2:30pm.

![image](https://user-images.githubusercontent.com/37711700/229325727-dc2b8f5f-5044-4fa2-9bf8-9cd46a654f03.png)

b3) Newly-created recurring events also display correctly in Full Calendar. Here’s a side-by-side comparison of FullCalendar and GoogleCalendar. The Full Calender event at 16:30 is supposed to be at 11:30.

![image](https://user-images.githubusercontent.com/37711700/229325679-b3a18df6-667a-4ba2-ab75-769b90e5023d.png)

So my question is, what are the settings/glitches that make some events display at the incorrect time in FullCalendar? Does anyone else have this problem? I somehow think it's a Google Calendar issues, but as the events are displaying correctly there, I wonder if a FullCalendar setting should be adjusted.

**Comment by davish** [comment] 2023-04-02 13:39
HI @amyoungil, thanks for submitting this issue. I believe it's related to other timezone issues, such as #311, #322 and #66. Unfortunately there is no timezone support currently in Full Calendar, and so if you import an ICS event where some events have timezone data and some do not, you may see an inconsistency like this. I am closing this as a duplicate of already open issues.

**Closed by davish** 2023-04-02 13:39 UTC
Labels: timezones
