### ISSUE TITLE
Rendering bug with Prism theme

### ISSUE THREAD

**Issue by Jackenheimer** [davish/obsidian-full-calendar#253] opened 2023-01-12 19:34 UTC
My issue is that when I use this plug in the Date and other buttons at the top are behind the banner at the top. I attached a screen shot of the issue I am having. If I can fix this in the files let me know. I am not a coder otherwise I would try.

I am using a couple of plug ins maybe this is causing it.

Dataview https://github.com/blacksmithgu/obsidian-dataview
Homepage https://github.com/mirnovov/obsidian-homepage
Obsidian Style Settings https://github.com/mgmeyers/obsidian-style-settings

![Obsidian_UC3OOgO0gD](https://user-images.githubusercontent.com/88523511/212163315-74a7660c-aa2b-4307-8f77-7a4672fd6fd1.png)

**Comment by davish** [comment] 2023-01-12 19:35
@Jackenheimer, what theme are you using?

**Comment by Jackenheimer** [comment] 2023-01-12 19:42
Prism https://github.com/mgmeyers/obsidian-style-settings

**Comment by davish** [comment] 2023-01-22 14:19
Unfortunately, I'm not able to reproduce this after installing style settings and the Prism theme.

**Comment by Jackenheimer** [comment] 2023-01-24 19:05
Well I really wanted to use this plug-in I will try to uninstall the style plugin and Prism to see if that fixes it, I am using Obsidian in Windows with the screen scaling at 350% as I have vision issues and my monitor is HDR 3840 x 2160 I will update this post after I try the obvious resetting Obsidian to OEM.

**Comment by Jackenheimer** [comment] 2023-01-24 23:24
As soon as I switch Prism back on it reverts to the top of the page being hidden behind that translucent banner.

I like the Prism theme and would like to continue using it - Hope you can think of something I can try to resolve this.

**Comment by davish** [comment] 2023-01-24 23:43
Could you submit an issue to the maintainer of Prism? It's possible they will be able to provide a fix better than I can

**Comment by Jackenheimer** [comment] 2023-01-25 03:12
Good call I will do that and let you know if I find anything out from the devs of that theme.

**Comment by davish** [comment] 2023-02-20 04:44
Closing this issue since it's being addressed by the Prism project.

**Closed by davish** 2023-02-20 04:44 UTC
Labels: bug, ui, integration
