### ISSUE TITLE
Obsidian stuck when clicking on event

### ISSUE THREAD

**Issue by asmagen** [davish/obsidian-full-calendar#280] opened 2023-02-15 18:06 UTC
**Describe the bug**
Clicking on event opens a small but empty overlay window, and the whole app is stuck.

**Comment by igelbox** [comment] 2023-02-19 20:00
@asmagen, сould you please provide some screenshots as well as debug messages from `View > Toggle Developer Tools`?

**Comment by davish** [comment] 2023-03-19 13:05
closing this issue because not enough details were given to reproduce it.

**Closed by davish** 2023-03-19 13:05 UTC
Labels: bug
