### ISSUE TITLE
Support for event descriptions

### ISSUE THREAD

**Issue by RadianttK** [davish/obsidian-full-calendar#291] opened 2023-02-24 04:18 UTC
There is already an open issue for viewing event details from imported read-only events [here](https://github.com/davish/obsidian-full-calendar/issues/97), but it would also be nice to add descriptions to newly created Full Note events.

Possibly this description could be displayed the main calendar view on the event but have it cut off with a "..." at the end if the description is too long.
- In this case the full description could be viewed by clicking on the event.

**Comment by davish** [comment] 2023-02-25 02:24
Duplicate of #152

**Closed by davish** 2023-02-25 02:24 UTC
