### ISSUE TITLE
Settings of open in sidebar are not maintained after reopening the app

### ISSUE THREAD

**Issue by asmagen** [davish/obsidian-full-calendar#278] opened 2023-02-15 18:01 UTC
**Describe the bug**
This is happening after restart for the calendar originally opened as "open in sidebar"
![Screenshot 2023-02-15 at 1 00 29 PM](https://user-images.githubusercontent.com/11299568/219114079-bd7cceb8-5e6b-45c8-8b7e-8293886e3cab.png)

**Comment by igelbox** [comment] 2023-02-19 19:49
Seems like a dupe of #277, doesn't it?

**Comment by davish** [comment] 2023-02-20 04:30
This does seem like a dupe. Thanks @igelbox for flagging!

**Closed** 2023-02-20 04:30 UTC
Labels: bug
