### ISSUE TITLE
Link notes to ics file in read view (cf. outlook)

### ISSUE THREAD

**Issue by dderom** [davish/obsidian-full-calendar#260] opened 2023-01-23 10:21 UTC
I import an ics (outlook) calendar from office 365. This is only in view mode, which is fine. 

Is it possible to link a note to an ics event? I would thusly be able to add meeting notes, meetings preps... even in the case I can not edit the meeting itself in Obsidian.

**Comment by davish** [comment] 2023-01-27 20:43
duplicate of #40

**Closed by davish** 2023-01-27 20:43 UTC

**Comment by MwumLi** [comment] 2023-04-23 06:51
How to import an ics from outlook ? @dderom
