### ISSUE TITLE
Links to events do not update on date change

### ISSUE THREAD

**Issue by hlageek** [davish/obsidian-full-calendar#254] opened 2023-01-16 18:59 UTC
Links to events created and managed by a Full Note local calendar do not update in other files when the event date (and therefore the file name of the event) is changed via Full Calendar.

**To Reproduce**
1. Create a link to a Full Calendar full note event from other .md file in the vault
2. In the Full Calendar, drag and drop the event to another day
3. The link in the .md file will not update and will become blank

**Expected behavior**
Links to events get updated when date changes are performed in Full Calendar.

When I change the date by renaming the event note manually, the links in other files get updated and the date changes in the Full Calendar as well. I suspect that when the date is changed by drag and drop the old event note gets deleted a new event note is created rather than simply renamed?

**Comment by davish** [comment] 2023-01-22 14:16
This is in fact a bug -- `vault.rename()` does not update backlinks. Thanks for submitting!

**Comment by davish** [comment] 2023-02-20 04:38
This is a duplicate of #64. A fix is on the way!

**Closed** 2023-02-20 04:39 UTC
Labels: bug
