### ISSUE TITLE
Include sub-folders of any folder defined in the configuration

### ISSUE THREAD

**Issue by ScottL7** [davish/obsidian-full-calendar#459] opened 2023-05-26 14:16 UTC
### Discussed in https://github.com/davish/obsidian-full-calendar/discussions/458

<div type='discussions-op-text'>

<sup>Originally posted by **ScottL7** May 26, 2023</sup>
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/davish/obsidian-full-calendar/discussions/categories/feature-requests) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/davish/obsidian-full-calendar/issues) didn't find any similar feature requests.

### 🔖 Feature description

I automatically break down my daily journals into a folder structure similar to the following: Journal/Daily Notes/YYYY-MM. Unfortunately, I must add a new folder for each month manually.

### ✔️ Solution

Include all files in sub-folders, recursively.

### 📝 Additional Context

_No response_</div>

**Comment by Spiralo-Idioide** [comment] 2023-05-30 10:34
Apparently the feature existed, but was removed because it causes problems when renaming or changing the date of an event.

But it is is definitely extremely useful and I agree it should be a feature of the plugin. Even if unsupported, and presented as such in the options.

My personal use case consists in creating one note for every class, each course has it's own folder. And I have a lot of different courses, more than 40. Which means I have to create a calendar for each and every one of them, for each semester. It's really not praticable.

**Comment by kmaustral** [comment] 2023-06-02 07:45
I'm sorry this feature doesn't exist any more. I file my events in their relevant project sub-folders.

**Comment by davish** [comment] 2023-09-06 13:47
Closing this thread as it is a duplicate of the discussion in #458

**Closed by davish** 2023-09-06 13:47 UTC
