### ISSUE TITLE
Add option for monthly view on mobile

### ISSUE THREAD

**Issue by gaerea** [davish/obsidian-full-calendar#241] opened 2022-12-28 00:32 UTC
Today i switched to full calendar.

All great, but i just found the mobile app does not have monthly view. This is big for me.

which is the best/easiest way to get monthly view on mobile, with full calendar?

**Comment by davish** [comment] 2023-02-26 22:58
duplicate of #48

**Closed by davish** 2023-02-26 22:58 UTC

**Comment by r7a1** [comment] 2023-05-05 12:22
I deeply agree with @gaerea. Monthly view is the last peace to the best app.
