### ISSUE TITLE
Trying to create a new event or upgrade a note to an event, I get an error

### ISSUE THREAD

**Issue by zachdaniel** [davish/obsidian-full-calendar#39] opened 2022-02-28 18:57 UTC
![CleanShot 2022-02-28 at 13 55 16](https://user-images.githubusercontent.com/5722339/156041991-8cd4990f-a2c7-499b-9d89-6e1c1c55f2a2.png)

I've upgraded to the latest released version (on BRAT). I don't have any more details than that, but will happily help debug if you point me where to look :)

**Comment by davish** [comment] 2022-03-01 03:14
Hi @zachdaniel, can you post a screenshot of the Full Calendar settings tab?

**Comment by zachdaniel** [comment] 2022-03-01 03:32
![CleanShot 2022-02-28 at 22 31 54](https://user-images.githubusercontent.com/5722339/156099758-bebd526b-47a6-4d4b-a23d-bd28a97a5ec0.png)
Yep! I have two remote ics calendars, but I'm selecting the `Events` calendar when creating the event.

**Comment by zachdaniel** [comment] 2022-03-01 03:33
The events calendar is also the only one that I'm prompted to select, which makes sense since google is one way sync.

**Comment by davish** [comment] 2022-03-01 04:35
Ah, I think I have an idea what the issue is. It has to do with how I'm passing the calendar ID along to the edit modal -- even though you're selecting "Events", the save function thinks you're trying to save to that first remote calendar. 

For now, can fix this by making sure your local calendar shows up at the top list of calendars in settings. There's no way to rearrange calendars right now, but you can change the third calendar type to remote, copy/paste the URL from the first calendar, and then change the first calendar to local with the "Events" folder. 

I'll start working on an actual fix so that this bug doesn't happen going forward. Thanks so much for the report @zachdaniel! I appreciate it and will let you know when the fix is released.

**Comment by zachdaniel** [comment] 2022-03-01 04:43
Ah, makes perfect sense, thanks!

**Comment by davish** [comment] 2022-03-01 05:15
@zachdaniel this should be fixed in `0.5.1` once Github Actions finishes packaging release 😄

**Closed** 2022-03-01 05:15 UTC
Labels: bug
