### ISSUE TITLE
Recurring Tasks

### ISSUE THREAD

**Issue by SealTea** [davish/obsidian-full-calendar#256] opened 2023-01-18 01:15 UTC
**Describe the bug**

When you create a recurring event and select the "Task Event"  option, no checkmark box is displayed in the calendar.  This is unlike singular task events that display a checkmark box.  I have certain assignments that repeat weekly that I would like to be able to check off.

**To Reproduce**
1. Go to 'create an event'
2. Click on 'Recurring event'
3. Click on 'Task event'
5. Return to calendar view
6. No checkmark will be displayed

**Expected behavior**
You would expect to have a series of recurring events with a checkmark displayed in front of them to match the singular events

**Screenshots**

<img width="390" alt="Screenshot 2023-01-17 171332" src="https://user-images.githubusercontent.com/109168079/213056732-d7b24939-74e4-4838-97b0-e58fdd7ddab3.png">
<img width="216" alt="Screenshot 2023-01-17 171401" src="https://user-images.githubusercontent.com/109168079/213056747-800878fb-5180-4a16-bd1c-b98a8cc50f55.png">

**Console Errors**
Go to `View->Toggle Developer Tools` and open up the JavaScript console, reproduce your bug, and copy/paste any logs you see there.

**Device info (please complete the following information):**
 - OS: Windows [e.g. iOS]
 - Plugin Version [e.g. `0.9.5`]

**Additional context**

**Comment by davish** [comment] 2023-01-22 14:15
Tasks and recurring events don't currently play well together. I'll re-tag this as an enhancement.

**Comment by realfr** [comment] 2023-02-01 16:00
This would be amazing!

**Comment by davish** [comment] 2023-02-12 02:58
this is a duplicate of #190

**Closed by davish** 2023-02-12 02:58 UTC
Labels: enhancement, parsing
