### ISSUE TITLE
Daily note does not work properly when note name format involves a subfolder

### ISSUE THREAD

**Issue by mrenow** [davish/obsidian-full-calendar#243] opened 2022-12-29 05:37 UTC
Hi there! Thanks so much for your plugin, it's exactly what I needed!

Now I keep my daily notes in folders for each week to decrease clutter - my format looks like this:

YY-WW/MM-DD-ddd

The issue is that my daily note events can be created but do not appear in the calendar if their year differs from the current year. This is the case on both mobile and my Ubuntu desktop. Tested event creation, dragging events from the current year to 2023 and 2021.

I am guessing that the event extraction is only looking at the note name, and not the full path?

**Comment by mrenow** [comment] 2022-12-30 00:48
I did some snooping around myself - the reason why this doesn't work is that obsidian's internal method of obtaining all daily notes does not handle folders.

Looking further, it seems like the `getAllDailyNotes()`, `getDateFromNote()`, and `getDateFromPath()` functions from `obsidian-daily-notes-interface` cant handle the case where the format involves a folder.

I managed to patch-fix the issue by writing new functions with ones written specifically for `granuality='day'`, to replace the obsidian-provided ones. I feel like this problem is quite unique to me, and it should be an issue with obsidian. Should I make a pull request here with the fix anyway?

**Comment by davish** [comment] 2022-12-30 06:09
@mrenow, thanks for the investigation! The PR probably makes most sense upstream at https://github.com/liamcain/obsidian-daily-notes-interface.

**Comment by mrenow** [comment] 2022-12-30 06:13
Ah! Thanks for the link to the repo - I had assumed the module was a core obsidian plugin.

**Comment by davish** [comment] 2023-01-01 02:35
Closing this issue since the issue is in a dependency. Let me know if you have any other questions!

**Closed by davish** 2023-01-01 02:35 UTC
Labels: bug, file management
