### ISSUE TITLE
decrease font size for 15 min events in Day/Week view

### ISSUE THREAD

**Issue by bcohen44** [davish/obsidian-full-calendar#120] opened 2022-05-26 10:28 UTC
if you have a 15 min event (or less) you cannot read the title in the Day/Week view.  Maybe decrease font size when the event is short?

**Comment by kohane27** [comment] 2022-05-27 22:08
+1
This is what happens with a 15-min interval event:

```
---
title: meditate
allDay: false
startTime: 20:30
endTime: 20:45
date: 2022-05-26
---
```
![screenshot-2022-05-28-06-07-08](https://user-images.githubusercontent.com/57322459/170795049-39ccc9d8-6257-4c72-a807-f394278ad602.png)

**Comment by davish** [comment] 2022-05-27 22:24
Probably related to issue #20

**Comment by davish** [comment] 2022-10-05 19:01
And #58

**Comment by davish** [comment] 2022-10-05 19:01
Closing as a duplicate of issue #20.

**Closed by davish** 2022-10-05 19:01 UTC
Labels: bug, ui
