### ISSUE TITLE
Request recurring date for month and year

### ISSUE THREAD

**Issue by Rsose** [davish/obsidian-full-calendar#131] opened 2022-07-06 05:39 UTC
Hi Davish
Could you please add a recurring date for each year or each month?
Because, usually the installments are per month or per year
I now have to set it to recur through the dates every weekend (so as not to forget)

Waiting for a reply
Thanks

**Comment by cja-github** [comment] 2022-09-02 10:27
Yes please. Basically, please copy the recurring options that Google Calendar has.

**Comment by davish** [comment] 2022-10-05 18:39
Closing this issue as a duplicate of #22

**Closed by davish** 2022-10-05 18:39 UTC
Labels: duplicate
