### ISSUE TITLE
Toggle calendar visibility

### ISSUE THREAD

**Issue by RadianttK** [davish/obsidian-full-calendar#293] opened 2023-02-24 04:30 UTC
It would be nice to have some easy to access buttons to toggle the visibility of individual calendars.
- Ideally this would be in the calendar itself, perhaps in the side somewhere
   -  I imagine it would easier though to just have it in the settings

Currently the only way to hide a calendar is to remove the calendar in the settings. To make it visible again you then need to add the file path back in the settings again. If you wanted it to be a specific color, you would also have to re-specify this every time you removed and re-added it.

**Comment by davish** [comment] 2023-02-25 02:24
Duplicate of #86

**Closed by davish** 2023-02-25 02:24 UTC
