### ISSUE TITLE
Support Tasks deadlines, scheduled and scheduling

### ISSUE THREAD

**Issue by neoromantic** [davish/obsidian-full-calendar#434] opened 2023-04-07 23:00 UTC
There's well-known [Tasks](https://obsidian-tasks-group.github.io/obsidian-tasks/) plugin, a lot of people use.

It supports setting deadline and scheduled dates.

Would be great, if those tasks appear on the calendar as well, without need to specify startTime / endTime manually.

Also, would be great if I could specify time in daily note for a task in plain text manner and it would be picked up by calendar, such as:

```
- [ ] 13:45 A client will come
- [ ] Work on a project 14:00-15:00
```

**Comment by davish** [comment] 2023-04-07 23:02
Duplicate of #376

**Closed** 2023-04-07 23:02 UTC
