### ISSUE TITLE
iCloud calendar slow to load entries when calendar is opened

### ISSUE THREAD

**Issue by gwthompson** [davish/obsidian-full-calendar#88] opened 2022-04-12 15:37 UTC
**Describe the bug**
I have connected my iCloud calendar using the app-specific password.  When I open the calendar it takes 30-35 seconds to display the entries on both my 13" M1 MacBook Pro and my 12.9" iPad Pro.

**To Reproduce**
Connect an iCloud calendar to Full Calendar. Open Full Calendar. Wait 30-35 seconds before seeing entries. If you close the calendar and open it again the same delay occurs.

**Expected behavior**
I expected the entries to show when I open Full Calendar or within a 1-2 seconds at most.

**Device info (please complete the following information):**
 - OS: MacOS 12.4 Beta and iPadOS 15.5 beta
 - Plugin Version: 0.61

Thanks!

**Comment by davish** [comment] 2022-04-13 15:15
Hi @gwthompson,
Thanks for submitting this bug, and sorry that you're not having a good experience with remote calendars right now. This is a known issue with the current feature, since remote calendars are not cached locally and are pulled down each time you open Full Calendar. Local cacheing is tracked in issue #77 if you want to keep up to date with progress on cacheing.

**Comment by davish** [comment] 2022-04-21 23:31
Triaging issues again and I'll be closing this since it's not a bug, just a missing feature that's already tracked in #77.

**Closed by davish** 2022-04-21 23:31 UTC
Labels: bug
