### ISSUE TITLE
Appointment creation interferes with native navigation in full calendar 

### ISSUE THREAD

**Issue by supersmart-at** [davish/obsidian-full-calendar#302] opened 2023-03-02 09:31 UTC
**Describe the bug**
The appointment event is triggered although you want to use a native navigation function of the fullcalendar.

**To Reproduce**
1. Opening the calendar in Month view and 
2. navigating to desired month with PREV / NEXT
3. Then clicking on the "intended" Day-Link 
4. This opens the Appointment Creation Event (Popup)

**Expected behavior**
I use this to navigate quickly into a desired month and date. Clicking on the Day-Link should navigate on the next loaded view (eg. 3 Days or 1 Day) and use this as working context. 
MacOS happens immediately on click; iPadOS with holding a delay (side note: apple pencil does not work like a click, uses same delay)

This should only happen, when selecting the Day-Link - otherwise the current behavior is good.

**Screenshots**

**Console Errors**
no errors, just ignoring a click event for navigation.

**Device info (please complete the following information):**
 - Mac OS Obsidian 1.1.6
 - iPad OS Obsidian 1.4.2

**Additional context**

**Comment by davish** [comment] 2023-03-09 00:03
This is a duplicate of #74.

**Closed by davish** 2023-03-09 00:03 UTC
Labels: bug
