### ISSUE TITLE
Default reminders for daily notes calendar items

### ISSUE THREAD

**Issue by pcause** [davish/obsidian-full-calendar#271] opened 2023-02-08 14:15 UTC
My online calendar creates a default reminder for my appointments/meetings.  In obsidian there is a reminder plugin but it would be a lot more convenient to have full-calendar use a default reminder time for appointments.  This could be done by full-calendar implementing reminders itself, or have an option to insert a reminder (in the reminder plugin format) to a created calendar item.

I suppose the dame could be done for notes based calendar items.

**Comment by davish** [comment] 2023-02-26 22:57
duplicate of #91

**Closed by davish** 2023-02-26 22:57 UTC
Labels: enhancement, event management
