### ISSUE TITLE
Toggle able from the calendar view

### ISSUE THREAD

**Issue by msmith1805** [davish/obsidian-full-calendar#114] opened 2022-05-20 20:43 UTC
It would be nice to be able to toggle the calendars on and off from the calendar view, and toggle which calendars can be toggled from the events settings.

(Thanks for this plugin! It was exactly what I was looking for!)

**Comment by 0-ft** [comment] 2022-05-20 22:43
Possible duplicate of https://github.com/davish/obsidian-full-calendar/issues/86

**Comment by davish** [comment] 2022-05-21 02:09
This is in fact a duplicate. Thanks for flagging @0-ft!

**Closed** 2022-05-21 02:09 UTC
Labels: duplicate
