### ISSUE TITLE
Keep the calendar when modifying an event

### ISSUE THREAD

**Issue by ascsanto** [davish/obsidian-full-calendar#95] opened 2022-04-15 22:53 UTC
It is kind of annoying that when i modify the title of an event i have every time to reselect the calendar in which it is already contained

**Comment by davish** [comment] 2022-04-17 18:38
Thanks for submitting @ascsanto -- this is definitely a bug. I'll add this to the "waiting for bugfix" milestone!

**Comment by davish** [comment] 2022-10-05 19:08
Duplicate of #142

**Closed by davish** 2022-10-05 19:08 UTC
Labels: bug, ui
