### ISSUE TITLE
When an event is made from the Calendar, endDate is one day after the chosen day

### ISSUE THREAD

**Issue by MiguelAHG** [davish/obsidian-full-calendar#98] opened 2022-04-20 01:17 UTC
**Describe the bug**
The bug occurs when I make an event that is not "all-day." The event appears to extend from the chosen day up to the next day. For example, if I choose April 20, 4 PM to 4:30 PM, it ends up becoming April 20, 4 PM to April 21, 4:30 PM. This is not the expected behavior.

**To Reproduce**
1. Open Full-Calendar in "month" view.
2. Click on April 20, 2022.
3. Make an event. Uncheck "all day" and set the time to 4:00 PM to 4:30 PM. Save the event.
4. Look at the calendar. The event lasts from April 20, 4:00 PM to April 21, 4:30 PM.
5. Look at the markdown note created. The endDate is 2022-04-21.

**Expected behavior**
I expected the event to last only within the chosen day; for example, April 20, 4:00 PM to April 20, 4:30 PM. The endDate should be 2022-04-20.

**Device info**
 - OS: Windows 10
 - Plugin Version: 0.6.1

**Comment by davish** [comment] 2022-04-21 23:25
Thanks for submitting this issue! It's a duplicate of #55 so I'm closing in favor of that issue.

**Closed by davish** 2022-04-21 23:25 UTC
Labels: bug
