### ISSUE TITLE
Singe Day Event Spans Over 2 Dates (with screenshots)

### ISSUE THREAD

**Issue by valiantgenomics** [davish/obsidian-full-calendar#184] opened 2022-11-14 01:21 UTC
When I create an event and give it a time range, for example from 08:30 to 09:30 AM on 04 Jan 2023, it glitches. Instead of being self-contained within the 04 Jan 2023 date box, it spans over the next box as well, i.e. 04-05 Jan.

![image](https://user-images.githubusercontent.com/111633318/201556124-2be227f7-0758-4a96-870d-2050e4c6c62b.png)

But if I select that the event "lasts all day" this bug disappears. 

Check the second screenshot below:

![image](https://user-images.githubusercontent.com/111633318/201556382-f90630e1-97a3-45c7-9cd4-7b68ca9ae47a.png)

**I'm using Obsidian on Linux:**
**OS:** Pop!_OS 22.04 LTS x86_64 
**Kernel:** 6.0.2-76060002-generic 

Thanks!!!

**Comment by davish** [comment] 2022-11-14 06:17
This is a dupe of #55. This is currently fixed in #183, but I haven't yet cut a release with the fix. I'll do that now, and the fix should be available in the next few minutes. Sorry about that!

**Closed by davish** 2022-11-14 06:17 UTC
Labels: bug, event management

**Comment by davish** [comment] 2022-11-14 06:18
@valiantgenomics this is now fixed in `0.7.6`. Cheers!

**Comment by valiantgenomics** [comment] 2022-11-14 09:25
@davish Wow awesome! I just checked the update and absolutely love how it shows time-ranged events as bullet points, but the all-day events as a highlight. It really helps differentiate what's what, just a glance.

Phenomenal, thanks a ton!!!!!!

**Comment by valiantgenomics** [comment] 2022-11-15 05:48
@davish Hey! Not sure if I should open a new issue for such a minor problem, but since I mentioned the bullet points already in my comment above, I thought it would be appropriate to add one more thing about them here as well.

There's this minor issue/bug where some of the time-ranged events that appear as bullet points, have a little black dot inside of them, while others do not.

It's difficult to spot on a smaller screen, but since I'm using a very large, high-res screen, it becomes quite evident. And it almost looks like they're different types of events, even though they are not.

I'm sharing a screenshot below, you'll probably have to zoom in a bit to see what I mean. 

But the red arrows point to the bullet points, which have black dots inside, whereas the yellow arrow points to the bullet points which don't have black dots inside.

![image](https://user-images.githubusercontent.com/111633318/201835803-3e94e77d-c7f0-44a8-8cf2-f6934fe7d5ad.png)

There's no rhyme or reason to how this is happening. Sometimes these black dots appear, other times they do not. So not sure how to exactly re-create the issue. But if you just add 2-3 events in one day and then another 1-2 following day, you should see the bug happening.

Just wanted to let you know! Thanks!!!

**Comment by davish** [comment] 2022-11-15 15:57
@valiantgenomics I'm guessing this is an issue with the underlying fullcalendar plugin and rendering on high-res screens. I think it might be better as an issue over on that repo: https://github.com/fullcalendar/fullcalendar
