### ISSUE TITLE
Sidebar calendar does not refresh remote events after it is opened

### ISSUE THREAD

**Issue by pcause** [davish/obsidian-full-calendar#239] opened 2022-12-26 14:34 UTC
**Describe the bug**
I added an event to my calendar and it isn't appearing on full calendar.  I am using an ICS calendar. I assume this is an update delay and don't see a way to force an update or what the frequency is

**To Reproduce**
add an item to an ics calendar at the source (I use m365) and event doesn't appear

**Expected behavior**
Either an update after an interval or a way to refresh the calendar

**Device info (please complete the following information):**
Windows 11
plugin 0.9.5

**Additional context**
Please either document the update interval or add a way to refresh if there is no automatic update.  best to allow a user specified update itnerval

**Comment by davish** [comment] 2022-12-26 16:15
1. Can you see the other events in this remote calendar?
1. If you exit Obsidian and re-open it with full calendar does the event
appear?
2. How many events are in this remote calendar?
3. Can you open the javascript console and see if there are any warnings or
errors?

**Comment by pcause** [comment] 2022-12-26 17:48
1 yes, i see the other events.  calendar is loaded and displayed in the sidebar.
2.  If I close the sidebar calendar and reopen it i see the event.  same on exiting.
3.  not sure but a lot in total, depending on what the plugin pulls for an interval
4. no errors in the console

**Comment by davish** [comment] 2022-12-26 17:52
This is an issue with the sidebar calendar. Right now it never refreshes after it is opened the first time. It is a pretty hard bug to fix with the current architecture, but hopefully I'll be able to close it with the big refactor I'm working on in #204.

**Comment by davish** [comment] 2022-12-26 17:53
@pcause if you are relying on ICS events, I would recommend avoiding using the sidebar calendar for now, unless you are okay with closing it and opening it every time you want to refresh events.

**Closed** 2023-03-16 22:48 UTC
Labels: bug, sync

**Comment by pcause** [comment] 2023-03-16 22:51
thanks, will try when I see the update

**Comment by davish** [comment] 2023-03-16 23:20
@pcause, the `0.10.0` update should be live now!

**Comment by pcause** [comment] 2023-03-17 11:27
didn't work.  updated and restarted.  when I opened the plugin in the sidebar I got this:

Revalidation failed with reason: Error: Event with given ID "some long set of numbers"  that was supposed to be added to calendar "ical::https://outlook.live.com/owa/calendar/...long uid.../calendar.ics" already exists in the EventStore within calendar "ical::https://outlook.live.com/owa/calendar/..long uid..../calendar.ics".

I deleted the ics and then re-added and got the same.  if i then open in the main window and not the sidebar I see the calendar but then get remote calendar filed to load.  even when i remove the plugin, restarted obsidian,  installed the plugin, added the ics calendar got same error.

**Comment by pcause** [comment] 2023-03-17 12:10
yes, same url

**Comment by davish** [comment] 2023-03-17 12:30
Thanks for the report @pcause. I was able to reproduce this bug, and filed #309 describing its root cause. A fix is on its way shortly.

**Comment by davish** [comment] 2023-03-17 13:06
#309 has been fixed and should be available in release `0.10.4` within the next few minutes.

**Comment by pcause** [comment] 2023-03-17 13:09
happy to help.  your note said to expect some issues.  will try when I see it released.  this is evolving and is a great plugin.

**Comment by pcause** [comment] 2023-03-17 13:41
NOPE.  says revalidation failed.  64696  type error.  cannot read properties of undefined.  (reading 'type')

**Comment by davish** [comment] 2023-03-17 13:49
My sincerest apologies @pcause. While I have typescript to a relatively strict setting, there are still a few `undefined`s that make it through without notifying me. This should be fixed in `0.10.5`, which is being generated and should be released in the next few minutes.

**Comment by davish** [comment] 2023-03-17 13:50
Thank you for your patience and for helping me make this plugin the best that it can be!

**Comment by pcause** [comment] 2023-03-17 13:51
no apology needed.  you are giving us this great plugin and we should all be happy to help and deal with a few issues at each release.

**Comment by pcause** [comment] 2023-03-17 14:12
now picking up my remote calendar.  I added my daily notes also as a calendar.  In the modal it had the right heading but after adding the calendar the events in today's note don't show up at all.  I have my ics and my daily notes as calendars.  BTW, the example in the readme shows a calendar list on the left but that doesn't appear.  Think you removed that at some point.

**Comment by pcause** [comment] 2023-03-17 14:15
ok, found that I could add an evenbt from the calendar.  my issue is that I doidn't have the startTime/endTime in my events.  I use tasks plugin and think I files a feature request about interoperability.  My fault.
