### ISSUE TITLE
Switching event from a non-default calendar does not create a page with the proper metadata

### ISSUE THREAD

**Issue by Admiralbr123** [davish/obsidian-full-calendar#189] opened 2022-11-17 10:07 UTC
This is a recurring problem, if I add an event to the non-default/first calendar first and then change it to some other calendar. The page is created but with no metadata and the event does not get added to the calendar. Please fix this issue. Thanks.

P.S Can we add partitions and events that span horizontally not vertically?

**Comment by davish** [comment] 2022-11-17 18:22
Thanks for submitting this bug report!

A few questions:
1. Do you fully create the event before trying to switch it to another calendar?
2. Are both calendars local calendars? Do you have any ICS or CalDAV calendars?

Please submit a separate feature request issue with your other request.

**Comment by davish** [comment] 2023-03-19 13:02
Closing this bug since I never got enough information to reproduce it.

**Closed by davish** 2023-03-19 13:02 UTC
Labels: bug, file management, event management
