### ISSUE TITLE
Interaction with calendar remote calendar items not available?

### ISSUE THREAD

**Issue by themanofsilver** [davish/obsidian-full-calendar#186] opened 2022-11-14 16:57 UTC
**What I am seeing**
I have added a Google Workspace calendar via secret iCal URL. I can see the calendar items, however if I double click on any of the imported events, I get an error pop-up stating "No frontmatter to edit for selected event". If I right-click on an item, I see a message stating "No actions available on remote events".

**To Reproduce**
See above

**Expected behavior**
I expect to be able to create a note for the specific event.

**Screenshots**
<img width="366" alt="CleanShot 2022-11-14 at 09 54 25@2x" src="https://user-images.githubusercontent.com/118138234/201719095-7fff8322-8e64-4766-8cfa-402acd95f619.png">
<img width="596" alt="CleanShot 2022-11-14 at 09 54 37@2x" src="https://user-images.githubusercontent.com/118138234/201719114-6f15e807-1263-48c9-a77c-fa1a4a1d81dc.png">

**Console Errors**
plugin:obsidian-full-calendar:52885 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
    at EventModal.eval (plugin:obsidian-full-calendar:52885:22)
    at Generator.next (<anonymous>)
    at eval (plugin:obsidian-full-calendar:66:61)
    at new Promise (<anonymous>)
    at __async (plugin:obsidian-full-calendar:50:10)
    at submit (plugin:obsidian-full-calendar:52883:42)
    at eval (plugin:obsidian-full-calendar:52241:11)
    at Generator.next (<anonymous>)
    at eval (plugin:obsidian-full-calendar:66:61)
    at new Promise (<anonymous>)
15plugin:obsidian-better-internal-link-inserter:78 setInterval
plugin:obsidian-full-calendar:52855 Full Calendar: No frontmatter to edit for selected event. EventApi3
eval @ plugin:obsidian-full-calendar:52855
plugin:obsidian-full-calendar:52855 Full Calendar: No frontmatter to edit for selected event. EventApi3
eval @ plugin:obsidian-full-calendar:52855
plugin:obsidian-full-calendar:52855 Full Calendar: No frontmatter to edit for selected event. EventApi3
eval @ plugin:obsidian-full-calendar:52855
plugin:obsidian-full-calendar:52855 Full Calendar: No frontmatter to edit for selected event. EventApi3
eval @ plugin:obsidian-full-calendar:52855
plugin:obsidian-full-calendar:52855 Full Calendar: No frontmatter to edit for selected event. EventApi3
eval @ plugin:obsidian-full-calendar:52855
plugin:obsidian-full-calendar:52855 Full Calendar: No frontmatter to edit for selected event. EventApi3
eval @ plugin:obsidian-full-calendar:52855
plugin:obsidian-full-calendar:52855 Full Calendar: No frontmatter to edit for selected event. EventApi3
eval @ plugin:obsidian-full-calendar:52855
plugin:obsidian-full-calendar:52855 Full Calendar: No frontmatter to edit for selected event. EventApi3 {_context: {…}, _def: {…}, _instance: {…}}
eval @ plugin:obsidian-full-calendar:52855
fulfilled @ plugin:obsidian-full-calendar:53
Promise.then (async)
step @ plugin:obsidian-full-calendar:65
eval @ plugin:obsidian-full-calendar:66
__async @ plugin:obsidian-full-calendar:50
editInModal @ plugin:obsidian-full-calendar:52845
eval @ plugin:obsidian-full-calendar:53921
eval @ plugin:obsidian-full-calendar:66
__async @ plugin:obsidian-full-calendar:50
eventClick @ plugin:obsidian-full-calendar:53913
Emitter2.trigger @ plugin:obsidian-full-calendar:43025
EventClicking2._this.handleSegClick @ plugin:obsidian-full-calendar:45875
eval @ plugin:obsidian-full-calendar:38945
plugin:obsidian-full-calendar:52855 Full Calendar: No frontmatter to edit for selected event. EventApi3 {_context: {…}, _def: {…}, _instance: {…}}
eval @ plugin:obsidian-full-calendar:52855
fulfilled @ plugin:obsidian-full-calendar:53
Promise.then (async)
step @ plugin:obsidian-full-calendar:65
eval @ plugin:obsidian-full-calendar:66
__async @ plugin:obsidian-full-calendar:50
editInModal @ plugin:obsidian-full-calendar:52845
eval @ plugin:obsidian-full-calendar:53921
eval @ plugin:obsidian-full-calendar:66
__async @ plugin:obsidian-full-calendar:50
eventClick @ plugin:obsidian-full-calendar:53913
Emitter2.trigger @ plugin:obsidian-full-calendar:43025
EventClicking2._this.handleSegClick @ plugin:obsidian-full-calendar:45875
eval @ plugin:obsidian-full-calendar:38945
plugin:obsidian-better-internal-link-inserter:78 setInterval
plugin:obsidian-full-calendar:52855 Full Calendar: No frontmatter to edit for selected event. EventApi3 {_context: {…}, _def: {…}, _instance: {…}}
eval @ plugin:obsidian-full-calendar:52855
fulfilled @ plugin:obsidian-full-calendar:53
Promise.then (async)
step @ plugin:obsidian-full-calendar:65
eval @ plugin:obsidian-full-calendar:66
__async @ plugin:obsidian-full-calendar:50
editInModal @ plugin:obsidian-full-calendar:52845
eval @ plugin:obsidian-full-calendar:53921
eval @ plugin:obsidian-full-calendar:66
__async @ plugin:obsidian-full-calendar:50
eventClick @ plugin:obsidian-full-calendar:53913
Emitter2.trigger @ plugin:obsidian-full-calendar:43025
EventClicking2._this.handleSegClick @ plugin:obsidian-full-calendar:45875
eval @ plugin:obsidian-full-calendar:38945
plugin:obsidian-full-calendar:52855 Full Calendar: No frontmatter to edit for selected event. EventApi3 {_context: {…}, _def: {…}, _instance: {…}}
eval @ plugin:obsidian-full-calendar:52855
fulfilled @ plugin:obsidian-full-calendar:53
Promise.then (async)
step @ plugin:obsidian-full-calendar:65
eval @ plugin:obsidian-full-calendar:66
__async @ plugin:obsidian-full-calendar:50
editInModal @ plugin:obsidian-full-calendar:52845
eval @ plugin:obsidian-full-calendar:53921
eval @ plugin:obsidian-full-calendar:66
__async @ plugin:obsidian-full-calendar:50
eventClick @ plugin:obsidian-full-calendar:53913
Emitter2.trigger @ plugin:obsidian-full-calendar:43025
EventClicking2._this.handleSegClick @ plugin:obsidian-full-calendar:45875
eval @ plugin:obsidian-full-calendar:38945

**Device info (please complete the following information):**
 - OS: macOS 13.0.1
 - Plugin Version 0.7.6

**Additional context**
N/A

**Comment by themanofsilver** [comment] 2022-11-14 17:23
Some additional comments from the error logs:

<img width="542" alt="CleanShot 2022-11-14 at 10 23 22@2x" src="https://user-images.githubusercontent.com/118138234/201725454-34f1c53a-a469-4edf-bd59-3865408d5cc2.png">

**Comment by davish** [comment] 2022-11-15 16:48
Duplicate of #135. Two-way sync is a feature that is not yet implemented that is tracked in issue #25. The only events that can be modified by Full Calendar currently are events backed by local notes.

**Closed by davish** 2022-11-15 16:48 UTC
Labels: bug

**Comment by FetchFast** [comment] 2023-06-29 12:44
The OP doesn't want 2-way sync. The OP wants to associate a note to a read-only calendar.

**Comment by FetchFast** [comment] 2023-06-29 12:46
Some of us have read only calendars provided to us, and we need to take notes on those events.
