### ISSUE TITLE
45 minute long event, the title is not visible

### ISSUE THREAD

**Issue by zsviczian** [davish/obsidian-full-calendar#58] opened 2022-03-13 06:49 UTC
I have many 45 minute long meetings. When a meeting is 30 minutes long, the title is rendered next to the time. When an event is longer than 45 minutes the title is rendered in the next row. I recommend only rendering the title in the next row, if the event is 60 minutes or longer.

**Comment by davish** [comment] 2022-10-05 19:01
Duplicate of #20.

**Closed by davish** 2022-10-05 19:01 UTC
Labels: bug, ui
