### ISSUE TITLE
The plugin does not work on the mobile version (iOS iPad)

### ISSUE THREAD

**Issue by Akira7118** [davish/obsidian-full-calendar#336] opened 2023-04-04 14:31 UTC
"The plugin is unable to open or work in the annotation mode on the mobile version (latest version of the plugin, iOS)

**Comment by davish** [comment] 2023-04-04 22:22
Sorry @Akira7118, but I'm closing this issue because there is not enough information to reproduce the failure. Please re-submit the issue and fill out the bug report template.

**Closed by davish** 2023-04-04 22:22 UTC
