### ISSUE TITLE
add note/data to ics entry - no sync back

### ISSUE THREAD

**Issue by pcause** [davish/obsidian-full-calendar#67] opened 2022-03-15 12:51 UTC
I love the ics support.  I'd like to be able to edit the entry or add a note to an ics entry.  Perhaps a note can be added for each ics calendar and then within that note there is some kind of "event" associated with the ics entry.  The entry can be a note spec or perhaps a "hide" indicator if I wish not to show something from a remote calendar because that event isnt relevant to me

**Comment by davish** [comment] 2022-03-15 21:35
Thanks for the feature request! This is a duplicate of #40, so I'm going to close this issue out.

**Closed by davish** 2022-03-15 21:35 UTC
