### ISSUE TITLE
Full Calendar not displaying in Obsidian using remote Google Calendar

### ISSUE THREAD

**Issue by cbailey17** [davish/obsidian-full-calendar#479] opened 2023-07-28 20:58 UTC
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/davish/obsidian-full-calendar/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and didn't find any similar reports.

### Expected Behavior

The calendar should display after running the appropriate command from the command palette. 

### Current behaviour

The screen remains blank and nothing displays 

![Screenshot from 2023-07-28 13-49-53](https://github.com/davish/obsidian-full-calendar/assets/31027014/ad7938ae-8b89-46db-a01b-b3a30c265160)

### JavaScript console output

![Screenshot from 2023-07-28 13-36-26](https://github.com/davish/obsidian-full-calendar/assets/31027014/8d0d85cd-f607-4eff-8ef5-7e2fa8e46c55)

### Steps to reproduce

1. Download Full Calendar plugin from the community plugins list
2. In the settings, add your secret remote .ics url under a new calendar
3. The plugin will load the calendar and seemingly no errors (as opposed to using a invalid url)
4. Open full calendar using the command 

### Calendar information

Im using a Google Calendar and pasting the secret .ics url as shown in the documentation 

### Which Operating Systems are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] Android
- [X] iOS

### Obsidian Version

1.3.5

### Full Calendar Plugin Version

0.10.7

### Checks

- [X] I have tried it with all other plugins disabled and the error still occurs.

### Comments

The calendar is public

**Comment by berlincount** [comment] 2023-08-06 13:41
Appears to be a duplicate of #460 ... I'm affected as well.

**Comment by berlincount** [comment] 2023-08-06 17:55
This bug actually seems to actually be #233 ...

**Comment by davish** [comment] 2023-09-06 13:49
Fixed by #484

**Closed by davish** 2023-09-06 13:49 UTC
Labels: bug
