### ISSUE TITLE
Customize recurring pattern

### ISSUE THREAD

**Issue by RadianttK** [davish/obsidian-full-calendar#295] opened 2023-02-24 05:41 UTC
Currently it seems the only option for recurring events is weekly.

It would be nice to have additional options such as monthly or fortnightly.
If nothing else, it would be good to at least have the option to create a custom pattern.
- i.e. recur every X days / years / months

**Comment by davish** [comment] 2023-02-25 02:23
duplicate of #22

**Closed by davish** 2023-02-25 02:23 UTC

**Comment by manveldavid** [comment] 2024-02-17 09:47
Can you give an example of a flexible recurring event please? What syntax should I use? Nothing about this in the documentation or on YouTube...

**Comment by manveldavid** [comment] 2024-02-17 09:48
add some .md file
