### ISSUE TITLE
Empty dialog when clicking events on Calendar main view

### ISSUE THREAD

**Issue by davidqqq** [davish/obsidian-full-calendar#266] opened 2023-02-02 05:38 UTC
**Describe the bug**

**To Reproduce**
1. Go to 'Calendar'
2. Click on any event
3. Empty dialog

**Expected behavior**
I dont know what exact content it should show. It is confusing that the content is empty.
**Screenshots**
![Screenshot 2023-02-02 at 1 37 19 PM](https://user-images.githubusercontent.com/21993144/216240928-0c012c75-d158-424f-9b13-bc8937402898.png)

**Console Errors**
Go to `View->Toggle Developer Tools` and open up the JavaScript console, reproduce your bug, and copy/paste any logs you see there.
```
plugin:obsidian-full-calendar:55689 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
    at eval (plugin:obsidian-full-calendar:55689:109)
    at Array.map (<anonymous>)
    at EditEvent (plugin:obsidian-full-calendar:55686:96)
    at renderWithHooks (plugin:obsidian-full-calendar:18330:26)
    at mountIndeterminateComponent (plugin:obsidian-full-calendar:20450:21)
    at beginWork (plugin:obsidian-full-calendar:21237:22)
    at HTMLUnknownElement.callCallback2 (plugin:obsidian-full-calendar:10940:22)
    at Object.invokeGuardedCallbackDev (plugin:obsidian-full-calendar:10965:24)
    at invokeGuardedCallback (plugin:obsidian-full-calendar:10999:39)
    at beginWork$1 (plugin:obsidian-full-calendar:24346:15)
```
**Device info (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Plugin Version [e.g. `0.1.3`] 0.9.5

**Additional context**

**Comment by davish** [comment] 2023-02-20 04:45
@davidqqq can you send a screenshot of your calendar settings?

**Comment by davish** [comment] 2023-04-08 14:20
Closing this issue because there has not been any elaboration and I haven't been able to reproduce. @davidqqq please submit another issue if the problem is still persisting on the most recent plugin version.

**Closed by davish** 2023-04-08 14:20 UTC
Labels: bug
