### ISSUE TITLE
Additional layouts

### ISSUE THREAD

**Issue by dxcore35** [davish/obsidian-full-calendar#214] opened 2022-12-05 15:06 UTC
Please get in contact with the developer of this task plugin. With your new addition to add additional tasks into calendar, you are eventually replicating his plugin.

https://github.com/702573N/Obsidian-Tasks-Calendar

The additional layout will be amazing. For example it may get usefull on mobile, or when adding note in sidebar. Your current view cannot fit in sidebar for example.

![](https://user-images.githubusercontent.com/59178587/203786071-eb97d99d-507b-4a92-9812-ba5cf6fd66ad.png)

**Comment by davish** [comment] 2022-12-05 22:30
Thank you for submitting this issue! This is mostly a duplicate of #51. I'm closing this because I don't plan to add fully customizable styling, since it would be quite difficult to support with FullCalendar.

**Closed by davish** 2022-12-05 22:30 UTC
